image: python:3.9-windowsservercore

stages:
  - build
  - release

build:
  stage: build
  script:
    - pip install uv
    - uv venv
    - .\.venv\Scripts\Activate.ps1
    - uv pip install -e ".[dev]"
    - pyinstaller --name rebirth-launcher --onefile --windowed --add-data "src/rebirthlauncher/resources;resources" src/rebirthlauncher/main.py
  artifacts:
    paths:
      - dist/rebirth-launcher.exe
  only:
    - tags

release:
  stage: release
  script:
    - glab release create $CI_COMMIT_TAG --assets-links dist/rebirth-launcher.exe
  only:
    - tags