name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Build executable
      run: |
        pyinstaller --name rebirth-launcher `
          --onefile `
          --windowed `
          --add-data "src/rebirthlauncher/resources;resources" `
          src/rebirthlauncher/main.py
          
    - name: Create version info
      run: |
        $version = "${{ github.ref_name }}"
        $splitFiles = Get-ChildItem -Filter "*.split.*" | Select-Object -ExpandProperty Name
        $versionInfo = @{
          version = $version
          release_date = (Get-Date -Format "yyyy-MM-dd")
          chunks = $splitFiles
          required_game_version = "1.1.0 Stable"
        } | ConvertTo-Json
        Set-Content -Path "src/version.json" -Value $versionInfo
          
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/rebirth-launcher.exe
          src/version.json
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 